version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: mindfuel-backend
    env_file:
      - ./backend/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: mindfuel-frontend
    environment:
      - NODE_ENV=production
      # Add NEXT_PUBLIC_API_URL if your frontend needs to know the backend URL
      # - NEXT_PUBLIC_API_URL=http://localhost:8000
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped 